language: node_js

node_js: 
  - "10"

# Install
before_script:
  - pyenv global 3.7
  - python --version
  - pip3 install -r requirements.txt --user

# Build and Test. Fails if package.json version hasn't been incremented on a PR
script:
  - npm run build
  - npm t
  - if [ $TRAVIS_PULL_REQUEST == true ] && [ $TRAVIS_BRANCH != "master" ]; then
      npm run tag;
    fi

# Tag and Publish
before_deploy:
  - npm run pre-deploy-test

deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
    condition: type != pull_request

after_deploy:
  - npm run release

notifications:
  email: false

cache:
  directories:
  - $HOME/.m2
